/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAcc: typeof import('./src/components/Services/AddAcc.vue')['default']
    AddPOI: typeof import('./src/components/Locations/AddPOI.vue')['default']
    AddTransp: typeof import('./src/components/Services/AddTransp.vue')['default']
    AddTrip: typeof import('./src/components/Trip/AddTrip.vue')['default']
    Alert: typeof import('./src/components/Utils/Alert.vue')['default']
    EditProfile: typeof import('./src/components/Auth/EditProfile.vue')['default']
    EditTrip: typeof import('./src/components/Trip/EditTrip.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    Logout: typeof import('./src/components/Auth/Logout.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MyTrips: typeof import('./src/components/Trip/MyTrips.vue')['default']
    PopularAccommodations: typeof import('./src/components/Analytics/PopularAccommodations.vue')['default']
    PopularCountries: typeof import('./src/components/Analytics/PopularCountries.vue')['default']
    PopularPOIs: typeof import('./src/components/Analytics/PopularPOIs.vue')['default']
    Profile: typeof import('./src/components/Auth/Profile.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotalUsers: typeof import('./src/components/Analytics/TotalUsers.vue')['default']
    TripDetail: typeof import('./src/components/Trip/TripDetail.vue')['default']
    TripView: typeof import('./src/components/Trip/TripView.vue')['default']
  }
}
