/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    HelloWorld: (typeof import("./src/components/HelloWorld.vue"))["default"];
    Home: (typeof import("./src/components/Home.vue"))["default"];
    Login: (typeof import("./src/components/Login.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
