/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AddTrip: (typeof import("./src/components/Trip/AddTrip.vue"))["default"];
    Alert: (typeof import("./src/components/Utils/Alert.vue"))["default"];
    Login: (typeof import("./src/components/Auth/Login.vue"))["default"];
    Logout: (typeof import("./src/components/Auth/Logout.vue"))["default"];
    Map: (typeof import("./src/components/Map.vue"))["default"];
    MyTrips: (typeof import("./src/components/Trip/MyTrips.vue"))["default"];
    Profile: (typeof import("./src/components/Auth/Profile.vue"))["default"];
    Register: (typeof import("./src/components/Auth/Register.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    TripDetail: (typeof import("./src/components/Trip/TripDetail.vue"))["default"];
    TripView: (typeof import("./src/components/Trip/TripView.vue"))["default"];
  }
}
