version: '3'

services:
  backend:
    build: 
      context: ./backend  
      dockerfile: Dockerfile 
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: ./django-setup.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

    env_file:
      - .env
    command: ["docker-entrypoint.sh", "postgres"]
    
volumes:
  pgdata:

networks:
  backend:
     driver: bridge