# Generated by Django 5.0.2 on 2024-03-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveljournal",
            name="entry_date",
        ),
    ]
