# Generated by Django 5.0.2 on 2024-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_remove_traveljournal_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default="2024-01-01"),
            preserve_default=False,
        ),
    ]
