# Generated by Django 5.0.2 on 2024-03-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportation",
            name="type",
            field=models.CharField(
                choices=[
                    ("car", "Car"),
                    ("bus", "Bus"),
                    ("train", "Train"),
                    ("plane", "Plane"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
