# Generated by Django 5.0.2 on 2024-03-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo", models.URLField(blank=True)),
                (
                    "birthdate",
                    models.DateField(blank=True, verbose_name="Date of Birth"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
                "indexes": [
                    models.Index(fields=["user"], name="authx_profi_user_id_baac9b_idx")
                ],
            },
        ),
    ]
