# Generated by Django 5.0.2 on 2024-03-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("trip", "0002_trip_pois"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="accommodations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="transportations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.transportation",
            ),
        ),
    ]
