# Generated by Django 5.0.2 on 2024-03-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("trip", "0003_trip_accommodations_trip_transportations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="accommodations",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="transportations",
        ),
        migrations.AddField(
            model_name="trip",
            name="accommodations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="trips",
                to="services.accommodation",
                verbose_name="Accommodations",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="transportations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="trips",
                to="services.transportation",
                verbose_name="Transportations",
            ),
        ),
    ]
