# Generated by Django 5.0.2 on 2024-03-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("trip", "0004_remove_trip_accommodations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="accommodations",
            field=models.ManyToManyField(
                related_name="trips",
                to="services.accommodation",
                verbose_name="Accommodations",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="transportations",
            field=models.ManyToManyField(
                related_name="trips",
                to="services.transportation",
                verbose_name="Transportations",
            ),
        ),
    ]
