# Generated by Django 5.0.2 on 2024-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0005_alter_trip_accommodations_alter_trip_transportations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
