# Generated by Django 5.0.2 on 2024-04-03 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0006_alter_trip_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trip",
            unique_together={("name", "organizer")},
        ),
    ]
