# Generated by Django 5.0.2 on 2024-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0007_alter_trip_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
