# Generated by Django 5.0.2 on 2024-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0008_trip_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="visibility",
            field=models.BooleanField(default=True, verbose_name="Visibility"),
        ),
    ]
